apiVersion: v1
kind: Secret
metadata:
  name: dev-cvmodels-secrets
data:
  access_key: QUtJQTZQN0tDR1dYS0k0TzRDWUc=
  secret_key: c2EvTTJCVWZ2b21jK3JxVW05c2piUmhqZFk4bk1UOWRIbExUNHJrTg==
  connection_string: bW9uZ29kYjovL2RldmRidXNlcjpYdFVoVkRKRFBFSGhAMTAuNTAuODAuNDQ6MjcwNzcvYWRtaW4=
