apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  REPLICAS: "{{ .Values.configMap.replicas }}"
  SERVICE: "{{ .Values.configMap.service }}"
  NAMESPACE: "{{ .Values.configMap.namespace }}"
  SHARE_DIR: "{{ .Values.configMap.shareDir }}"
  DEFAULT_REPLICATION_FACTOR: "{{ .Values.configMap.defaultReplicationFactor }}"
  DEFAULT_MIN_INSYNC_REPLICAS: "{{ .Values.configMap.defaultMinInsyncReplicas }}"
  NETWORK_THREAD: "{{ .Values.configMap.networkThread }}"
  CLUSTERID: "{{ .Values.configMap.clusterId }}"

