apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: kafka-app
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: 'broker'
      port: {{ .Values.service.broker.port }}
      protocol: TCP
      targetPort: {{ .Values.service.broker.targetPort }}
   
    - name: 'controller'
      port: {{ .Values.service.controller.port }}
      protocol: TCP
      targetPort: {{ .Values.service.controller.targetPort }}
  selector:
    app: kafka-app

